name: Build and Deploy Flask App to Azure

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the repository code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Use the version of Python required for your Flask app

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assuming you have a requirements.txt with Flask dependencies

      - name: Run tests (optional)
        run: |
          pytest  # Assuming you're using pytest for unit tests

      - name: Build the app (if applicable)
        run: |
          # Flask apps generally do not need a build step like React apps
          echo "Flask app setup complete"

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Only run the deploy step if the build step was successful
    steps:
      - name: Deploy to Azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APP_NAME }}  # Azure App Service Name
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}  # Azure Publish Profile XML
          package: .  # Deploy the entire repository (current directory) to Azure
